import type { Locale } from "@/i18n/config";
import type { StandardDictionary, StandardStageTranslation, TechnicalTermKey } from "@/i18n/types";
import { JOURNEY_STAGES } from "@/data/stages";
import { HERBS_SPICES_PROCESS_STAGES } from "@/data/herbs-spices/process";

const terms: Record<Locale, Record<TechnicalTermKey, string>> = {
  en: { source:"Source",preparation:"Preparation",sorting:"Sorting",grading:"Grading",packing:"Packing",qualityControl:"Quality Control",lot:"Lot",batch:"Batch",traceability:"Traceability",inspection:"Inspection",specification:"Specification",condition:"Condition",packaging:"Packaging",harvest:"Harvest",handling:"Handling",storage:"Storage",export:"Export",documentation:"Documentation",commercialHandover:"Commercial Handover" },
  ar: { source:"المصدر",preparation:"التجهيز",sorting:"الفرز",grading:"التدريج",packing:"التعبئة",qualityControl:"مراقبة الجودة",lot:"شحنة إنتاج",batch:"دفعة",traceability:"التتبّع",inspection:"الفحص",specification:"المواصفة",condition:"الحالة",packaging:"التغليف",harvest:"الحصاد",handling:"المناولة",storage:"التخزين",export:"التصدير",documentation:"المستندات",commercialHandover:"التسليم التجاري" },
  ru: { source:"Источник",preparation:"Подготовка",sorting:"Сортировка",grading:"Калибровка",packing:"Упаковка",qualityControl:"Контроль качества",lot:"Партия",batch:"Производственная партия",traceability:"Прослеживаемость",inspection:"Инспекция",specification:"Спецификация",condition:"Состояние",packaging:"Тара и упаковка",harvest:"Сбор урожая",handling:"Обращение с продукцией",storage:"Хранение",export:"Экспорт",documentation:"Документация",commercialHandover:"Коммерческая передача" },
  de: { source:"Ursprung",preparation:"Aufbereitung",sorting:"Sortierung",grading:"Klassierung",packing:"Packen",qualityControl:"Qualitätskontrolle",lot:"Partie",batch:"Charge",traceability:"Rückverfolgbarkeit",inspection:"Prüfung",specification:"Spezifikation",condition:"Zustand",packaging:"Verpackung",harvest:"Ernte",handling:"Handhabung",storage:"Lagerung",export:"Export",documentation:"Dokumentation",commercialHandover:"Kommerzielle Übergabe" },
  fr: { source:"Origine",preparation:"Préparation",sorting:"Tri",grading:"Calibrage",packing:"Conditionnement",qualityControl:"Contrôle qualité",lot:"Lot",batch:"Lot de production",traceability:"Traçabilité",inspection:"Inspection",specification:"Spécification",condition:"État",packaging:"Emballage",harvest:"Récolte",handling:"Manutention",storage:"Stockage",export:"Export",documentation:"Documentation",commercialHandover:"Remise commerciale" },
};

const produceStages: Record<Locale, readonly StandardStageTranslation[]> = {
  en: JOURNEY_STAGES.map((stage) => ({ name:stage.name,kicker:stage.kicker,status:stage.status,stamp:stage.stamp,headline:stage.headline ?? stage.name,copy:stage.copy,proofOutput:stage.proofOutput ?? "",imageAlt:`${stage.name} - ${stage.headline ?? stage.name}`,facts:stage.facts })),
  ar: [
    {name:"المصدر",kicker:"01 / المصدر",status:"تم اختيار المنشأ",stamp:"اعتماد المصدر",headline:"مختار للمشتري، لا للمخزن.",copy:"تتم مواءمة المزارع والحقل والمحصول مع متطلبات الوجهة قبل إدراج شحنة الإنتاج في برنامج التصدير.",proofOutput:"مطابقة مواصفة المشتري قبل الحصاد.",imageAlt:"اختيار المصدر والمحصول للتصدير",facts:[["الضبط","اختيار المنشأ"],["المواءمة مع","مواصفة المشتري"],["المخرج","شحنة إنتاج محددة"]]},
    {name:"الفحص",kicker:"02 / الفحص",status:"تم التحقق من الجودة",stamp:"قبول مراقبة الجودة",headline:"فحص الجودة قبل انتقال المنتج.",copy:"يتم التحقق ميدانيًا من الحالة الفعلية والعيار ومعايير الدرجة قبل المعالجة.",proofOutput:"التحقق من الدرجة والحالة.",imageAlt:"فحص جودة المنتجات الزراعية",facts:[["الضبط","فحص الجودة"],["المواءمة مع","معايير الدرجة"],["المخرج","شحنة إنتاج مقبولة"]]},
    {name:"التجهيز",kicker:"03 / التجهيز",status:"تم تجهيز الشكل",stamp:"اعتماد العملية",headline:"تجهيز وفق مواصفة الوجهة.",copy:"يُجهز المنتج بدقة لطلبات التصدير الطازجة أو المجمدة أو المجففة ضمن حدود التفاوت المتفق عليها مع المشتري.",proofOutput:"مواءمة الشكل ومتطلبات الطلب.",imageAlt:"تجهيز المنتجات وفق مواصفة التصدير",facts:[["الضبط","مناولة المعالجة"],["المواءمة مع","الشكل المطلوب"],["المخرج","منتج زراعي مجهز"]]},
    {name:"التعبئة",kicker:"04 / التعبئة",status:"اكتملت التعبئة",stamp:"اعتماد العبوة",headline:"تعبئة للرحلة المقبلة.",copy:"تجميع الوحدات ووضع الملصقات وفحص العرض بما يلائم متطلبات سوق الوجهة وثبات المنتج أثناء النقل.",proofOutput:"اعتماد عبوة التصدير.",imageAlt:"تعبئة المنتجات الزراعية للتصدير",facts:[["الضبط","صيغة التعبئة"],["المواءمة مع","متطلبات الوجهة"],["المخرج","وحدات تصدير"]]},
    {name:"التحكم",kicker:"05 / التحكم المناخي",status:"تأمين سلسلة التبريد",stamp:"مراقبة الحفظ",headline:"الحفاظ على الحالة خلال المناولة.",copy:"تُدار سلسلة التبريد والرطوبة والجو المحيط بصورة مستمرة حتى التصريح بالشحن.",proofOutput:"تأمين سلسلة التحكم المناخي.",imageAlt:"التحكم في ظروف حفظ المنتجات",facts:[["الضبط","مناولة التخزين"],["المواءمة مع","حالة المنتج"],["المخرج","شحنة جاهزة للإفراج"]]},
    {name:"التسليم",kicker:"06 / التسليم",status:"تم التصريح للتصدير",stamp:"مصرح بالشحن",headline:"مصرح بها. موثقة. جاهزة للتحرك.",copy:"تستكمل المستندات والمناولة والتسليم التصديري رحلة شحنة الإنتاج الخاضعة للضبط.",proofOutput:"مصرح بالإرسال الدولي.",imageAlt:"التسليم النهائي للشحنة المصرح بتصديرها",facts:[["الضبط","التصريح للتصدير"],["المواءمة مع","الإرسال الدولي"],["المخرج","تسليم الشحنة"]]},
  ],
  ru: [
    {name:"Источник",kicker:"01 / ИСТОЧНИК",status:"Источник выбран",stamp:"Источник согласован",headline:"Отбор для покупателя, а не для склада.",copy:"Производитель, поле и культура сопоставляются с требованиями рынка назначения до включения партии в экспортную программу.",proofOutput:"Соответствие спецификации покупателя определено до сбора.",imageAlt:"Отбор источника и культуры для экспорта",facts:[["Контроль","Выбор происхождения"],["Соответствие","Спецификация покупателя"],["Результат","Идентифицированная партия"]]},
    {name:"Инспекция",kicker:"02 / ИНСПЕКЦИЯ",status:"Качество проверено",stamp:"Принято ОКК",headline:"Качество проверяется до перемещения.",copy:"Физическое состояние, калибр и параметры сорта проверяются на месте до обработки.",proofOutput:"Сортность и состояние проверены.",imageAlt:"Инспекция качества сельхозпродукции",facts:[["Контроль","Инспекция качества"],["Соответствие","Критерии сортности"],["Результат","Принятая партия"]]},
    {name:"Подготовка",kicker:"03 / ПОДГОТОВКА",status:"Формат подготовлен",stamp:"Процесс согласован",headline:"Подготовлено по спецификации назначения.",copy:"Продукция точно подготавливается под задания на экспорт в свежем, замороженном или сушёном виде в пределах согласованных допусков покупателя.",proofOutput:"Формат согласован с заданием.",imageAlt:"Подготовка продукции по экспортной спецификации",facts:[["Контроль","Технологическое обращение"],["Соответствие","Требуемый формат"],["Результат","Подготовленная продукция"]]},
    {name:"Упаковка",kicker:"04 / УПАКОВКА",status:"Упаковка завершена",stamp:"Упаковка согласована",headline:"Упаковано для предстоящего пути.",copy:"Формирование грузовых единиц, маркировка и проверка представления выполняются с учётом требований рынка назначения и устойчивости при перевозке.",proofOutput:"Экспортная упаковка согласована.",imageAlt:"Упаковка сельхозпродукции для экспорта",facts:[["Контроль","Формат упаковки"],["Соответствие","Задание рынка назначения"],["Результат","Экспортные единицы"]]},
    {name:"Контроль",kicker:"05 / КЛИМАТИЧЕСКИЙ КОНТРОЛЬ",status:"Холодовая цепь обеспечена",stamp:"Хранение контролируется",headline:"Состояние сохраняется при обращении.",copy:"Холодовая цепь, влажность и атмосфера непрерывно контролируются до разрешения на отправку.",proofOutput:"Климатическая цепь обеспечена.",imageAlt:"Контроль условий хранения продукции",facts:[["Контроль","Складское обращение"],["Соответствие","Состояние продукта"],["Результат","Партия к выпуску"]]},
    {name:"Передача",kicker:"06 / ПЕРЕДАЧА",status:"Экспорт разрешён",stamp:"Разрешено к отправке",headline:"Разрешено. Учтено. Готово к отправке.",copy:"Документация, обращение с продукцией и экспортная передача завершают контролируемый путь партии.",proofOutput:"Разрешено к международной отправке.",imageAlt:"Передача партии, разрешённой к экспорту",facts:[["Контроль","Экспортное оформление"],["Соответствие","Международная отправка"],["Результат","Передача груза"]]},
  ],
  de: [
    {name:"Ursprung",kicker:"01 / URSPRUNG",status:"Ursprung ausgewählt",stamp:"Quelle freigegeben",headline:"Für den Käufer ausgewählt, nicht für das Lager.",copy:"Erzeuger, Feld und Kultur werden vor Aufnahme der Partie in das Exportprogramm mit den Anforderungen des Zielmarkts abgeglichen.",proofOutput:"Käuferspezifikation vor der Ernte abgeglichen.",imageAlt:"Auswahl von Ursprung und Kultur für den Export",facts:[["Kontrolle","Ursprungsauswahl"],["Abgestimmt auf","Käuferspezifikation"],["Ergebnis","Identifizierte Partie"]]},
    {name:"Prüfung",kicker:"02 / PRÜFUNG",status:"Qualität geprüft",stamp:"QS akzeptiert",headline:"Qualität geprüft, bevor die Ware weitergeht.",copy:"Physischer Zustand, Kaliber und Güteparameter werden vor der Verarbeitung vor Ort geprüft.",proofOutput:"Güte und Zustand geprüft.",imageAlt:"Qualitätsprüfung landwirtschaftlicher Erzeugnisse",facts:[["Kontrolle","Qualitätsprüfung"],["Abgestimmt auf","Gütekriterien"],["Ergebnis","Akzeptierte Partie"]]},
    {name:"Aufbereitung",kicker:"03 / AUFBEREITUNG",status:"Format vorbereitet",stamp:"Prozess freigegeben",headline:"Nach Zielspezifikation aufbereitet.",copy:"Präzise Aufbereitung für frische, tiefgekühlte oder getrocknete Exportbriefings innerhalb der vereinbarten Käufertoleranzen.",proofOutput:"Format und Briefing abgestimmt.",imageAlt:"Aufbereitung nach Exportspezifikation",facts:[["Kontrolle","Prozesshandhabung"],["Abgestimmt auf","Erforderliches Format"],["Ergebnis","Aufbereitete Erzeugnisse"]]},
    {name:"Packen",kicker:"04 / VERPACKUNG",status:"Packen abgeschlossen",stamp:"Packung freigegeben",headline:"Für den weiteren Weg verpackt.",copy:"Einheitenbildung, Kennzeichnung und Präsentationsprüfung erfolgen mit Blick auf Anforderungen des Zielmarkts und Transportstabilität.",proofOutput:"Exportverpackung freigegeben.",imageAlt:"Verpackung landwirtschaftlicher Erzeugnisse für den Export",facts:[["Kontrolle","Packformat"],["Abgestimmt auf","Zielmarktbriefing"],["Ergebnis","Exporteinheiten"]]},
    {name:"Kontrolle",kicker:"05 / KLIMAKONTROLLE",status:"Kühlkette gesichert",stamp:"Lagerung überwacht",headline:"Zustand bei der Handhabung erhalten.",copy:"Kühlkette, Feuchtigkeit und Atmosphäre werden bis zur Versandfreigabe kontinuierlich gesteuert.",proofOutput:"Klimakette gesichert.",imageAlt:"Kontrolle der Lagerbedingungen",facts:[["Kontrolle","Lagerhandhabung"],["Abgestimmt auf","Produktzustand"],["Ergebnis","Freigabepartie"]]},
    {name:"Übergabe",kicker:"06 / ÜBERGABE",status:"Für Export freigegeben",stamp:"Versandfreigabe",headline:"Freigegeben. Erfasst. Versandbereit.",copy:"Dokumentation, Handhabung und Exportübergabe schließen den kontrollierten Weg der Partie ab.",proofOutput:"Für den internationalen Versand freigegeben.",imageAlt:"Übergabe der für den Export freigegebenen Partie",facts:[["Kontrolle","Exportfreigabe"],["Abgestimmt auf","Internationaler Versand"],["Ergebnis","Sendungsübergabe"]]},
  ],
  fr: [
    {name:"Origine",kicker:"01 / ORIGINE",status:"Origine sélectionnée",stamp:"Source validée",headline:"Sélectionné pour l'acheteur, pas pour le stock.",copy:"Le producteur, la parcelle et la culture sont rapprochés des exigences de destination avant l'entrée du lot dans le programme export.",proofOutput:"Spécification acheteur rapprochée avant récolte.",imageAlt:"Sélection de l'origine et de la culture pour l'export",facts:[["Contrôle","Sélection de l'origine"],["Aligné sur","Spécification acheteur"],["Résultat","Lot identifié"]]},
    {name:"Inspection",kicker:"02 / INSPECTION",status:"Qualité contrôlée",stamp:"Accepté par le contrôle qualité",headline:"La qualité est contrôlée avant tout transfert.",copy:"L'état physique, le calibre et les paramètres de catégorie sont contrôlés sur site avant transformation.",proofOutput:"Catégorie et état contrôlés.",imageAlt:"Inspection qualité des produits agricoles",facts:[["Contrôle","Inspection qualité"],["Aligné sur","Critères de catégorie"],["Résultat","Lot accepté"]]},
    {name:"Préparation",kicker:"03 / PRÉPARATION",status:"Format préparé",stamp:"Processus validé",headline:"Préparé selon la spécification de destination.",copy:"Préparation précise pour les cahiers des charges export en frais, surgelé ou séché, dans les tolérances convenues avec l'acheteur.",proofOutput:"Format aligné sur le cahier des charges.",imageAlt:"Préparation selon la spécification export",facts:[["Contrôle","Manutention du processus"],["Aligné sur","Format requis"],["Résultat","Produit préparé"]]},
    {name:"Conditionnement",kicker:"04 / EMBALLAGE",status:"Conditionnement terminé",stamp:"Emballage validé",headline:"Conditionné pour le trajet à venir.",copy:"Mise en unités, étiquetage et contrôle de présentation selon les exigences du marché de destination et la stabilité en transit.",proofOutput:"Emballage export validé.",imageAlt:"Conditionnement des produits agricoles pour l'export",facts:[["Contrôle","Format de conditionnement"],["Aligné sur","Cahier des charges destination"],["Résultat","Unités export"]]},
    {name:"Contrôle",kicker:"05 / CONTRÔLE CLIMATIQUE",status:"Chaîne du froid sécurisée",stamp:"Conservation surveillée",headline:"État maintenu pendant la manutention.",copy:"La chaîne du froid, l'humidité et l'atmosphère sont gérées en continu jusqu'à l'autorisation d'expédition.",proofOutput:"Chaîne climatique sécurisée.",imageAlt:"Contrôle des conditions de stockage",facts:[["Contrôle","Manutention en stockage"],["Aligné sur","État du produit"],["Résultat","Lot prêt à libérer"]]},
    {name:"Remise",kicker:"06 / REMISE",status:"Export autorisé",stamp:"Autorisé à expédier",headline:"Autorisé. Comptabilisé. Prêt à partir.",copy:"La documentation, la manutention et la remise export achèvent le parcours contrôlé du lot.",proofOutput:"Autorisé pour l'expédition internationale.",imageAlt:"Remise du lot autorisé à l'export",facts:[["Contrôle","Autorisation export"],["Aligné sur","Expédition internationale"],["Résultat","Remise de l'expédition"]]},
  ],
};

const controls: Record<Locale, readonly { number:string; title:string; description:string }[]> = {
  en:[{number:"01",title:"Sourcing",description:"Origin and programme selection."},{number:"02",title:"Quality control",description:"Inspection against agreed criteria."},{number:"03",title:"Traceability",description:"Lot identity across the journey."},{number:"04",title:"Packing",description:"Format aligned to buyer requirements."},{number:"05",title:"Storage",description:"Handling around product condition."},{number:"06",title:"IQF processing",description:"Controlled preparation for frozen lines."},{number:"07",title:"Certifications",description:"Documentation for programme needs."},{number:"08",title:"Sustainability",description:"Responsible choices across operations."}],
  ar:[{number:"01",title:"التوريد",description:"اختيار المنشأ وبرنامج التوريد."},{number:"02",title:"مراقبة الجودة",description:"الفحص وفق المعايير المتفق عليها."},{number:"03",title:"التتبّع",description:"هوية شحنة الإنتاج طوال الرحلة."},{number:"04",title:"التعبئة",description:"صيغة تتوافق مع متطلبات المشتري."},{number:"05",title:"التخزين",description:"مناولة تراعي حالة المنتج."},{number:"06",title:"معالجة IQF",description:"تجهيز مضبوط لخطوط التجميد."},{number:"07",title:"الشهادات",description:"مستندات تلائم احتياجات البرنامج."},{number:"08",title:"الاستدامة",description:"خيارات مسؤولة عبر العمليات."}],
  ru:[{number:"01",title:"Закупка",description:"Выбор происхождения и программы."},{number:"02",title:"Контроль качества",description:"Проверка по согласованным критериям."},{number:"03",title:"Прослеживаемость",description:"Идентичность партии на всём пути."},{number:"04",title:"Упаковка",description:"Формат по требованиям покупателя."},{number:"05",title:"Хранение",description:"Обращение с учётом состояния продукта."},{number:"06",title:"Обработка IQF",description:"Контролируемая подготовка линий заморозки."},{number:"07",title:"Сертификация",description:"Документация под требования программы."},{number:"08",title:"Устойчивость",description:"Ответственные решения в операциях."}],
  de:[{number:"01",title:"Beschaffung",description:"Auswahl von Ursprung und Programm."},{number:"02",title:"Qualitätskontrolle",description:"Prüfung nach vereinbarten Kriterien."},{number:"03",title:"Rückverfolgbarkeit",description:"Partieidentität über den gesamten Weg."},{number:"04",title:"Packen",description:"Format gemäß Käuferanforderungen."},{number:"05",title:"Lagerung",description:"Handhabung nach Produktzustand."},{number:"06",title:"IQF-Verarbeitung",description:"Kontrollierte Aufbereitung für Tiefkühllinien."},{number:"07",title:"Zertifizierungen",description:"Dokumentation für Programmanforderungen."},{number:"08",title:"Nachhaltigkeit",description:"Verantwortungsvolle Entscheidungen im Betrieb."}],
  fr:[{number:"01",title:"Approvisionnement",description:"Sélection de l'origine et du programme."},{number:"02",title:"Contrôle qualité",description:"Inspection selon les critères convenus."},{number:"03",title:"Traçabilité",description:"Identité du lot sur tout le parcours."},{number:"04",title:"Conditionnement",description:"Format aligné sur les besoins acheteur."},{number:"05",title:"Stockage",description:"Manutention adaptée à l'état du produit."},{number:"06",title:"Traitement IQF",description:"Préparation contrôlée pour les lignes surgelées."},{number:"07",title:"Certifications",description:"Documentation selon les besoins du programme."},{number:"08",title:"Durabilité",description:"Choix responsables dans les opérations."}],
};

const ui = {
  en:{hero:["One lot.","Every step","controlled.","From Egyptian field selection to export handover, every AGRICA shipment follows one controlled process."],proof:["Journey stage progress","Handover","Export handover","CONTROLLED SPECIFICATION","Built around the destination.","Market","Grade","Pack","Condition","Handover","JOURNEY STATUS","SOURCE","INSPECT","PREPARE","PACK","CONTROL","CLEARED","EXPORT CLEARED","FULL SPECIFICATION CERTIFIED","ONE SHIPMENT · SIX CONTROLLED STAGES","Ready to discuss your next export programme?","Export programme","Egypt","of","Export journey stages","From origin to arrival","Controlled at every step.","Trusted at every destination.","Choose the products and destination. AGRICA will shape the export brief around your programme."]},
  ar:{hero:["شحنة إنتاج واحدة.","كل خطوة","خاضعة للضبط.","من اختيار الحقل المصري إلى التسليم التصديري، تمر كل شحنة من أجريكا عبر عملية واحدة مضبوطة."],proof:["تقدم مراحل الرحلة","التسليم","التسليم التصديري","مواصفة مضبوطة","مصممة حول الوجهة.","السوق","الدرجة","التعبئة","الحالة","التسليم","حالة الرحلة","المصدر","الفحص","التجهيز","التعبئة","التحكم","مصرح","مصرح للتصدير","المواصفة الكاملة معتمدة","شحنة واحدة · ست مراحل مضبوطة","هل نناقش برنامج التصدير القادم؟","برنامج التصدير","مصر","من","مراحل رحلة التصدير","من المنشأ إلى الوصول","ضبط في كل خطوة.","ثقة في كل وجهة.","اختر المنتجات والوجهة، وستصوغ أجريكا متطلبات التصدير حول برنامجك."]},
  ru:{hero:["Одна партия.","Каждый этап","под контролем.","От выбора египетского поля до экспортной передачи каждая поставка AGRICA проходит единый контролируемый процесс."],proof:["Ход этапов поставки","Передача","Экспортная передача","КОНТРОЛИРУЕМАЯ СПЕЦИФИКАЦИЯ","С учётом пункта назначения.","Рынок","Сортность","Упаковка","Состояние","Передача","СТАТУС ПОСТАВКИ","ИСТОЧНИК","ИНСПЕКЦИЯ","ПОДГОТОВКА","УПАКОВКА","КОНТРОЛЬ","РАЗРЕШЕНО","ЭКСПОРТ РАЗРЕШЁН","ПОЛНАЯ СПЕЦИФИКАЦИЯ ПОДТВЕРЖДЕНА","ОДНА ПОСТАВКА · ШЕСТЬ КОНТРОЛИРУЕМЫХ ЭТАПОВ","Обсудим вашу следующую экспортную программу?","Экспортная программа","Египет","из","Этапы экспортного пути","От происхождения до прибытия","Контроль на каждом этапе.","Доверие в каждом пункте назначения.","Выберите продукты и направление. AGRICA сформирует экспортное задание под вашу программу."]},
  de:{hero:["Eine Partie.","Jeder Schritt","kontrolliert.","Von der Auswahl ägyptischer Felder bis zur Exportübergabe folgt jede AGRICA-Sendung einem kontrollierten Prozess."],proof:["Fortschritt der Prozessstufen","Übergabe","Exportübergabe","KONTROLLIERTE SPEZIFIKATION","Am Zielmarkt ausgerichtet.","Markt","Güte","Packung","Zustand","Übergabe","PROZESSSTATUS","URSPRUNG","PRÜFUNG","AUFBEREITUNG","PACKEN","KONTROLLE","FREIGEGEBEN","FÜR EXPORT FREIGEGEBEN","VOLLSTÄNDIGE SPEZIFIKATION BESTÄTIGT","EINE SENDUNG · SECHS KONTROLLIERTE STUFEN","Ihr nächstes Exportprogramm besprechen?","Exportprogramm","Ägypten","von","Stufen des Exportprozesses","Vom Ursprung bis zur Ankunft","Kontrolliert bei jedem Schritt.","Verlässlich an jedem Ziel.","Wählen Sie Produkte und Zielmarkt. AGRICA erstellt daraus das Exportbriefing für Ihr Programm."]},
  fr:{hero:["Un lot.","Chaque étape","sous contrôle.","De la sélection des parcelles égyptiennes à la remise export, chaque expédition AGRICA suit un processus contrôlé unique."],proof:["Progression des étapes","Remise","Remise export","SPÉCIFICATION CONTRÔLÉE","Construite autour de la destination.","Marché","Catégorie","Emballage","État","Remise","ÉTAT DU PARCOURS","ORIGINE","INSPECTION","PRÉPARATION","CONDITIONNEMENT","CONTRÔLE","AUTORISÉ","EXPORT AUTORISÉ","SPÉCIFICATION COMPLÈTE CERTIFIÉE","UNE EXPÉDITION · SIX ÉTAPES CONTRÔLÉES","Échangeons sur votre prochain programme export.","Programme export","Égypte","sur","Étapes du parcours export","De l'origine à l'arrivée","Contrôlé à chaque étape.","Fiable à chaque destination.","Choisissez les produits et la destination. AGRICA structurera le cahier des charges export autour de votre programme."]},
} as const;

const registerUi: Record<Locale, readonly [string,string,string,string,string]> = {
  en:["Control register","Eight connected disciplines","Not a checkpoint.","A system.","Operational disciplines remain connected around the same specification, lot and destination."],
  ar:["سجل الضبط","ثمانية تخصصات مترابطة","ليست نقطة فحص.","بل منظومة.","تظل التخصصات التشغيلية مترابطة حول المواصفة وشحنة الإنتاج والوجهة نفسها."],
  ru:["Реестр контроля","Восемь связанных направлений","Не отдельная проверка.","А система.","Операционные направления связаны единой спецификацией, партией и пунктом назначения."],
  de:["Kontrollregister","Acht verbundene Disziplinen","Kein einzelner Prüfpunkt.","Ein System.","Die operativen Disziplinen bleiben über dieselbe Spezifikation, Partie und Destination verbunden."],
  fr:["Registre de contrôle","Huit disciplines connectées","Pas un simple point de contrôle.","Un système.","Les disciplines opérationnelles restent liées à la même spécification, au même lot et à la même destination."],
};

const herbStages: Record<Locale, readonly {title:string;shortLabel:string;description:string}[]> = {
  en: HERBS_SPICES_PROCESS_STAGES.map(({title,shortLabel,description})=>({title,shortLabel,description})),
  ar:[{title:"المصدر",shortLabel:"المادة الخام",description:"تبدأ الرحلة بالمادة الزراعية وبالشكل الذي يُراد أن يصبح عليه المكوّن."},{title:"التجهيز",shortLabel:"تشكيل المادة",description:"تُجهز المادة لمرحلتها التالية عبر مناولة مدروسة وتحضير يناسب الشكل المطلوب."},{title:"التجفيف",shortLabel:"خفض الرطوبة",description:"تُخفض الرطوبة بالأسلوب المختار بما يلائم الشكل المستهدف للمكوّن."},{title:"التدريج",shortLabel:"تحديد الشكل",description:"تُنظم المادة وفق صيغتها التجارية وطريقة عرضها المستهدفة."},{title:"التعبئة",shortLabel:"تجهيز الصيغة",description:"ينتقل المكوّن المجهز إلى صيغة التعبئة المحددة في المتطلبات التجارية."},{title:"التصدير",shortLabel:"التسليم التجاري",description:"يُجهز المكوّن للتسليم التجاري وللخطوة التالية في رحلة الإمداد."}],
  ru:[{title:"Источник",shortLabel:"Сырьё",description:"Путь начинается с сельскохозяйственного сырья и формы ингредиента, которую планируется получить."},{title:"Подготовка",shortLabel:"Формирование материала",description:"Материал готовится к следующему этапу посредством продуманного обращения и подготовки под конкретную форму."},{title:"Сушка",shortLabel:"Снижение влажности",description:"Влажность снижается выбранным способом с учётом требуемой формы ингредиента."},{title:"Калибровка",shortLabel:"Определение формы",description:"Материал организуется по предполагаемому коммерческому формату и представлению."},{title:"Упаковка",shortLabel:"Подготовка формата",description:"Подготовленный ингредиент поступает в формат упаковки, указанный в коммерческом задании."},{title:"Экспорт",shortLabel:"Коммерческая передача",description:"Ингредиент готовится к коммерческой передаче и следующему этапу дальнейшей поставки."}],
  de:[{title:"Ursprung",shortLabel:"Rohmaterial",description:"Der Weg beginnt beim Agrarrohstoff und der vorgesehenen Form des Zutatenprodukts."},{title:"Aufbereitung",shortLabel:"Material formen",description:"Das Material wird durch bedachte Handhabung und formspezifische Aufbereitung auf die nächste Stufe vorbereitet."},{title:"Trocknung",shortLabel:"Feuchtigkeit reduzieren",description:"Die Feuchtigkeit wird mit dem gewählten Verfahren für die vorgesehene Zutatenform reduziert."},{title:"Klassierung",shortLabel:"Form definieren",description:"Das Material wird nach dem vorgesehenen Handelsformat und der Präsentation geordnet."},{title:"Packen",shortLabel:"Format vorbereiten",description:"Die aufbereitete Zutat gelangt in das im kommerziellen Briefing festgelegte Packformat."},{title:"Export",shortLabel:"Kommerzielle Übergabe",description:"Die Zutat wird für die kommerzielle Übergabe und den nächsten Schritt der Lieferkette vorbereitet."}],
  fr:[{title:"Origine",shortLabel:"Matière première",description:"Le parcours commence avec la matière agricole et la forme d'ingrédient visée."},{title:"Préparation",shortLabel:"Façonner la matière",description:"La matière est préparée pour l'étape suivante par une manutention réfléchie et adaptée à la forme."},{title:"Séchage",shortLabel:"Réduire l'humidité",description:"L'humidité est réduite selon l'approche retenue pour l'expression d'ingrédient visée."},{title:"Calibrage",shortLabel:"Définir la forme",description:"La matière est organisée selon le format commercial et la présentation prévus."},{title:"Conditionnement",shortLabel:"Préparer le format",description:"L'ingrédient préparé passe au format de conditionnement défini dans le cahier des charges commercial."},{title:"Export",shortLabel:"Remise commerciale",description:"L'ingrédient est préparé pour la remise commerciale et l'étape suivante de son parcours d'approvisionnement."}],
};

const herbUi = {
 en:["AGRICA / HERBS & SPICES","From source","to form.","A structured journey from agricultural origin to a prepared ingredient format.","Material / control","The material changes.","The discipline does not.","Each intended form shapes the journey. The final sequence and controls will follow the approved ingredient specification.","Process stages","Stage","Current","Next step","Prepared for the next commercial step.","Continue with the provisional ingredient catalogue or begin a conversation around your brief."],
 ar:["أجريكا / الأعشاب والتوابل","من المصدر","إلى الشكل.","رحلة منظمة من المنشأ الزراعي إلى مكوّن مُجهز بصيغته المطلوبة.","المادة / الضبط","تتغير المادة.","ويبقى الانضباط.","يشكل كل شكل مستهدف مسار الرحلة. وسيتبع التسلسل النهائي وعناصر الضبط مواصفة المكوّن المعتمدة.","مراحل العملية","المرحلة","الحالية","الخطوة التالية","مُجهز للخطوة التجارية التالية.","تابع إلى كتالوج المكونات المؤقت أو ابدأ نقاشًا حول متطلباتك."],
 ru:["AGRICA / ТРАВЫ И СПЕЦИИ","От источника","к форме.","Структурированный путь от сельскохозяйственного происхождения до подготовленного формата ингредиента.","Материал / контроль","Материал меняется.","Дисциплина остаётся.","Каждая целевая форма определяет путь. Окончательная последовательность и контроль будут следовать утверждённой спецификации ингредиента.","Этапы процесса","Этап","Текущий","Следующий шаг","Подготовлено к следующему коммерческому этапу.","Перейдите к предварительному каталогу ингредиентов или обсудите с нами ваше задание."],
 de:["AGRICA / KRÄUTER & GEWÜRZE","Vom Ursprung","zur Form.","Ein strukturierter Weg vom landwirtschaftlichen Ursprung zum aufbereiteten Zutatenformat.","Material / Kontrolle","Das Material verändert sich.","Die Disziplin bleibt.","Jede Zielform prägt den Weg. Die endgültige Abfolge und Kontrolle folgen der freigegebenen Zutatenspezifikation.","Prozessstufen","Stufe","Aktuell","Nächster Schritt","Für den nächsten kommerziellen Schritt vorbereitet.","Weiter zum vorläufigen Zutatenkatalog oder ein Gespräch über Ihr Briefing beginnen."],
 fr:["AGRICA / HERBES & ÉPICES","De l'origine","à la forme.","Un parcours structuré de l'origine agricole à un format d'ingrédient préparé.","Matière / contrôle","La matière évolue.","La rigueur demeure.","Chaque forme visée façonne le parcours. La séquence et les contrôles définitifs suivront la spécification d'ingrédient approuvée.","Étapes du processus","Étape","En cours","Étape suivante","Préparé pour la prochaine étape commerciale.","Poursuivez vers le catalogue provisoire d'ingrédients ou échangez avec nous sur votre cahier des charges."],
} as const;

export function standardDictionary(locale: Locale): StandardDictionary {
  const p=ui[locale], h=herbUi[locale];
  const stageRecords=Object.fromEntries(JOURNEY_STAGES.map((stage,index)=>[stage.id,produceStages[locale][index]]));
  const herbRecords=Object.fromEntries(HERBS_SPICES_PROCESS_STAGES.map((stage,index)=>[stage.id,herbStages[locale][index]]));
  return { terms:terms[locale], produce:{ hero:{titleLead:p.hero[0],titleEmphasis:p.hero[1],titleClose:p.hero[2],description:p.hero[3]}, stages:stageRecords, controls:controls[locale], ui:{progressLabel:p.proof[0],handover:p.proof[1],exportHandover:p.proof[2],controlledSpecification:p.proof[3],destinationTitle:p.proof[4],proofPillars:p.proof.slice(5,10),journeyStatus:p.proof[10],completionSteps:p.proof.slice(11,17),exportCleared:p.proof[17],fullSpecificationCertified:p.proof[18],oneShipment:p.proof[19],discussProgramme:p.proof[20],exportProgramme:p.proof[21],egypt:p.proof[22],of:p.proof[23],selectorLabel:p.proof[24],closeEyebrow:p.proof[25],closeTitle:p.proof[26],closeEmphasis:p.proof[27],closeDescription:p.proof[28],registerEyebrow:registerUi[locale][0],registerStrap:registerUi[locale][1],registerLead:registerUi[locale][2],registerEmphasis:registerUi[locale][3],registerDescription:registerUi[locale][4]}}, herbs:{hero:{eyebrow:h[0],titleLead:h[1],titleEmphasis:h[2],description:h[3]},stages:herbRecords,interlude:{eyebrow:h[4],title:h[5],emphasis:h[6],description:h[7]},progress:{label:h[8],stage:h[9],current:h[10]},final:{eyebrow:h[11],title:h[12],description:h[13]}} };
}
