import type { Locale } from "@/i18n/config";
import type { ProductCardFieldLabelKey } from "@/types/product-card-content";

const labels = {
  en: {
    typicalEgyptianSeason: "Typical Egyptian Season",
    typicalEgyptianExportWindow: "Typical Egyptian Export Window",
    typicalEgyptianHarvest: "Typical Egyptian Harvest",
    typicalEgyptianFreshSeason: "Typical Egyptian Fresh Season",
    season: "Season",
    cropWindow: "Crop Window",
    variety: "Variety",
    varietyColour: "Variety / Colour",
    productType: "Product Type",
    productForm: "Product Form",
    productStage: "Product Stage",
    type: "Type",
    colourType: "Colour / Type",
    dispatchMaturity: "Dispatch Maturity",
    intendedUse: "Intended Use",
    sizeCalibre: "Size / Calibre",
    berryCalibre: "Berry Calibre",
    berryBunchSpecification: "Berry / Bunch Specification",
    calibre: "Calibration",
    cut: "Cut",
    cutCalibration: "Cut / Calibration",
    leafCutSpecification: "Leaf / Cut Specification",
    leafParticleSize: "Leaf / Particle Size",
    particleSize: "Particle Size",
    sizeCount: "Size / Count",
    cutSize: "Cut / Size",
    componentCalibration: "Component Calibration",
    qualitySpecification: "Quality Specification",
    potatoSpecification: "Potato Specification",
    productComposition: "Product Composition",
    preparation: "Preparation",
    processing: "Processing",
    treatment: "Treatment",
    packFormat: "Pack Format",
    storage: "Storage",
    frozenStorage: "Frozen Storage",
    relativeHumidity: "Relative Humidity",
    handling: "Handling",
    buyerNote: "Buyer Note",
    buyerSpecification: "Buyer Specification",
  },
  ar: {
    typicalEgyptianSeason: "الموسم المصري المعتاد",
    typicalEgyptianExportWindow: "فترة التصدير المصرية المعتادة",
    typicalEgyptianHarvest: "موسم الحصاد المصري المعتاد",
    typicalEgyptianFreshSeason: "الموسم المصري الطازج المعتاد",
    season: "الموسم",
    cropWindow: "فترة المحصول",
    variety: "الصنف",
    varietyColour: "الصنف / اللون",
    productType: "نوع المنتج",
    productForm: "شكل المنتج",
    productStage: "مرحلة المنتج",
    type: "النوع",
    colourType: "اللون / النوع",
    dispatchMaturity: "درجة النضج عند الشحن",
    intendedUse: "الاستخدام المقصود",
    sizeCalibre: "الحجم / العيار",
    berryCalibre: "عيار الثمار",
    berryBunchSpecification: "مواصفات الثمار / العنقود",
    calibre: "المعايرة",
    cut: "التقطيع",
    cutCalibration: "التقطيع / المعايرة",
    leafCutSpecification: "مواصفات الأوراق / التقطيع",
    leafParticleSize: "حجم الأوراق / الجزيئات",
    particleSize: "حجم الجزيئات",
    sizeCount: "الحجم / العدد",
    cutSize: "التقطيع / الحجم",
    componentCalibration: "معايرة المكونات",
    qualitySpecification: "مواصفات الجودة",
    potatoSpecification: "مواصفات البطاطس",
    productComposition: "تركيبة المنتج",
    preparation: "التجهيز",
    processing: "المعالجة",
    treatment: "المعاملة",
    packFormat: "شكل التعبئة",
    storage: "التخزين",
    frozenStorage: "التخزين المجمد",
    relativeHumidity: "الرطوبة النسبية",
    handling: "التداول",
    buyerNote: "ملاحظة للمشتري",
    buyerSpecification: "مواصفات المشتري",
  },
  ru: {
    typicalEgyptianSeason: "Типичный сезон в Египте",
    typicalEgyptianExportWindow: "Типичный экспортный период Египта",
    typicalEgyptianHarvest: "Типичный сбор урожая в Египте",
    typicalEgyptianFreshSeason: "Типичный сезон свежей продукции в Египте",
    season: "Сезон",
    cropWindow: "Период урожая",
    variety: "Сорт",
    varietyColour: "Сорт / цвет",
    productType: "Тип продукта",
    productForm: "Форма продукта",
    productStage: "Стадия продукта",
    type: "Тип",
    colourType: "Цвет / тип",
    dispatchMaturity: "Зрелость при отгрузке",
    intendedUse: "Назначение",
    sizeCalibre: "Размер / калибр",
    berryCalibre: "Калибр ягод",
    berryBunchSpecification: "Параметры ягод / грозди",
    calibre: "Калибровка",
    cut: "Нарезка",
    cutCalibration: "Нарезка / калибровка",
    leafCutSpecification: "Параметры листа / нарезки",
    leafParticleSize: "Размер листа / частиц",
    particleSize: "Размер частиц",
    sizeCount: "Размер / количество",
    cutSize: "Нарезка / размер",
    componentCalibration: "Калибровка компонентов",
    qualitySpecification: "Параметры качества",
    potatoSpecification: "Параметры картофеля",
    productComposition: "Состав продукта",
    preparation: "Подготовка",
    processing: "Обработка",
    treatment: "Обработка",
    packFormat: "Формат упаковки",
    storage: "Хранение",
    frozenStorage: "Хранение в замороженном виде",
    relativeHumidity: "Относительная влажность",
    handling: "Обращение",
    buyerNote: "Примечание для покупателя",
    buyerSpecification: "Спецификация покупателя",
  },
  de: {
    typicalEgyptianSeason: "Typische ägyptische Saison",
    typicalEgyptianExportWindow: "Typisches ägyptisches Exportfenster",
    typicalEgyptianHarvest: "Typische ägyptische Ernte",
    typicalEgyptianFreshSeason: "Typische ägyptische Frischsaison",
    season: "Saison",
    cropWindow: "Erntefenster",
    variety: "Sorte",
    varietyColour: "Sorte / Farbe",
    productType: "Produkttyp",
    productForm: "Produktform",
    productStage: "Produktstufe",
    type: "Typ",
    colourType: "Farbe / Typ",
    dispatchMaturity: "Reife bei Versand",
    intendedUse: "Verwendungszweck",
    sizeCalibre: "Größe / Kaliber",
    berryCalibre: "Beerenkaliber",
    berryBunchSpecification: "Beeren- / Traubenspezifikation",
    calibre: "Kalibrierung",
    cut: "Schnitt",
    cutCalibration: "Schnitt / Kalibrierung",
    leafCutSpecification: "Blatt- / Schnittspezifikation",
    leafParticleSize: "Blatt- / Partikelgröße",
    particleSize: "Partikelgröße",
    sizeCount: "Größe / Anzahl",
    cutSize: "Schnitt / Größe",
    componentCalibration: "Komponentenkalibrierung",
    qualitySpecification: "Qualitätsspezifikation",
    potatoSpecification: "Kartoffelspezifikation",
    productComposition: "Produktzusammensetzung",
    preparation: "Vorbereitung",
    processing: "Verarbeitung",
    treatment: "Behandlung",
    packFormat: "Verpackungsformat",
    storage: "Lagerung",
    frozenStorage: "Tiefkühllagerung",
    relativeHumidity: "Relative Luftfeuchtigkeit",
    handling: "Handhabung",
    buyerNote: "Hinweis für Käufer",
    buyerSpecification: "Käuferspezifikation",
  },
  fr: {
    typicalEgyptianSeason: "Saison égyptienne type",
    typicalEgyptianExportWindow: "Période d’exportation égyptienne type",
    typicalEgyptianHarvest: "Récolte égyptienne type",
    typicalEgyptianFreshSeason: "Saison égyptienne type en frais",
    season: "Saison",
    cropWindow: "Période de récolte",
    variety: "Variété",
    varietyColour: "Variété / couleur",
    productType: "Type de produit",
    productForm: "Forme du produit",
    productStage: "Stade du produit",
    type: "Type",
    colourType: "Couleur / type",
    dispatchMaturity: "Maturité à l’expédition",
    intendedUse: "Utilisation prévue",
    sizeCalibre: "Taille / calibre",
    berryCalibre: "Calibre des baies",
    berryBunchSpecification: "Spécification des baies / grappes",
    calibre: "Calibrage",
    cut: "Coupe",
    cutCalibration: "Coupe / calibrage",
    leafCutSpecification: "Spécification feuille / coupe",
    leafParticleSize: "Taille feuille / particules",
    particleSize: "Taille des particules",
    sizeCount: "Taille / nombre",
    cutSize: "Coupe / taille",
    componentCalibration: "Calibrage des composants",
    qualitySpecification: "Spécification qualité",
    potatoSpecification: "Spécification pomme de terre",
    productComposition: "Composition du produit",
    preparation: "Préparation",
    processing: "Transformation",
    treatment: "Traitement",
    packFormat: "Format d’emballage",
    storage: "Stockage",
    frozenStorage: "Stockage surgelé",
    relativeHumidity: "Humidité relative",
    handling: "Manutention",
    buyerNote: "Note acheteur",
    buyerSpecification: "Spécification acheteur",
  },
} as const satisfies Readonly<Record<Locale, Readonly<Record<ProductCardFieldLabelKey, string>>>>;

export function productCardFieldLabel(locale: Locale, key: ProductCardFieldLabelKey): string {
  return labels[locale][key];
}

export const PRODUCT_CARD_FIELD_LABELS = labels;
